## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [150]:
array = np.random.randint(1, 10, 20)
print(array)
result = np.where(np.logical_and(array > 3, array < 8), -array, array)
print(result)

[2 3 9 1 2 8 3 5 9 6 9 5 7 5 4 8 2 5 8 9]
[ 2  3  9  1  2  8  3 -5  9 -6  9 -5 -7 -5 -4  8  2 -5  8  9]


**2.** Заменить максимальный элемент случайного массива на 0

In [90]:
print(array)
result = np.where(array == array.max(), 0, array)
print(result)
matrix = np.random.randint(1, 10, (5,5))

[6 3 6 2 4 3 4 9 1 4 9 4 1 3 8 2 6 3 2 3]
[6 3 6 2 4 3 4 0 1 4 0 4 1 3 8 2 6 3 2 3]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [107]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [145]:
A = np.random.randint(0,5,(8,3))
print(A)
B = np.random.randint(0,5,(2,2))
print(B)

L1 = np.where(np.reshape(np.in1d(A, B[0]), (8,3)).sum(axis=1), True, False)
L2 = np.where(np.reshape(np.in1d(A, B[1]), (8,3)).sum(axis=1), True, False)
lines = (L1 * L2 == True).nonzero()[0]
print(lines)

[[2 4 4]
 [0 4 4]
 [0 0 1]
 [4 1 4]
 [2 1 4]
 [3 0 1]
 [4 0 0]
 [1 3 1]]
[[1 3]
 [4 1]]
[2 3 4 5 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [157]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 2 3]
 [1 4 4]
 [3 3 3]
 [1 2 2]
 [4 1 0]
 [3 4 0]
 [3 0 4]
 [4 3 0]
 [3 4 1]
 [2 2 2]]
[[1 2 3]
 [1 4 4]
 [1 2 2]
 [4 1 0]
 [3 4 0]
 [3 0 4]
 [4 3 0]
 [3 4 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [4]:
matrix = np.random.randint(1, 5, (10,3))
print(matrix)
matrix = np.unique(matrix, axis=0)
print(matrix)

[[4 1 3]
 [4 1 4]
 [4 3 2]
 [3 4 1]
 [2 3 2]
 [3 1 2]
 [2 3 1]
 [1 2 2]
 [3 1 2]
 [1 2 4]]
[[1 2 2]
 [1 2 4]
 [2 3 1]
 [2 3 2]
 [3 1 2]
 [3 4 1]
 [4 1 3]
 [4 1 4]
 [4 3 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [59]:
# without numpy
import random
matrix = [[random.randint(1, 5) for j in range(3)] for i in range(4)]
print(matrix)
result = 1
for i in range(min(len(matrix),len(matrix[0]))):
    if matrix[i][i] != 0:
        result *= matrix[i][i]
print(result)
# numpy
matrix = np.random.randint(1, 5, (5,4))
print(matrix)
result = np.prod(np.diag(matrix)[np.diag(matrix).nonzero()[0]])
print(result)



[[1, 4, 3], [3, 2, 2], [5, 3, 5], [2, 5, 4]]
10
[[2 4 1 3]
 [3 4 2 1]
 [2 2 3 4]
 [1 1 3 4]
 [3 1 3 2]]
96


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [171]:
# without numpy
import random
x = [random.randint(0, 3) for i in range(4)]
print(x)
y = [random.randint(0, 3) for i in range(4)]
print(y)
print(sorted(x)==sorted(y))

# numpy
condition = True
x = np.random.randint(0, 3, 4)
print(x)
y = np.random.randint(0, 3, 4)
print(y)
x_val, x_count = np.unique(x, return_counts=True)
y_val, y_count = np.unique(y, return_counts=True)
if np.array_equal(x_val, y_val):
    if not np.array_equal(x_count, y_count):
        condition = False
else:
    condition = False
print(condition)

[1, 0, 0, 1]
[3, 0, 1, 3]
False
[1 1 1 0]
[0 0 2 0]
False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [328]:
# without numpy
max = 0
x = [random.randint(0, 5) for i in range(10)]
print(x)
for i in range(1,10):
    if x[i-1] == 0:
        if max < x[i]:
            max = x[i]
print(max)

# numpy
x = np.random.randint(0, 5, 10)
print(x)
try:
    max = np.max(x[(x[0:-1] == 0).nonzero()[0]+1]) 
except ValueError:
    max = 'no such element'
    
print(max)

[4, 5, 4, 4, 4, 4, 0, 2, 4, 1]
2
[4 4 4 3 3 1 4 4 4 1]
no such element


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [336]:
# without numpy
x = [random.randint(0, 9) for i in range(10)]
print(x)
count = [0 for i in range(10)]
for i in range(10):
    count[x[i]] += 1
result_val = []
result_count = []
for i in range(10):
    if count[x[i]] != 0:
        if not x[i] in result_val:
            result_val.append(x[i])
            result_count.append(count[x[i]])
print(result_val)
print(result_count)

# numpy
x = np.random.randint(0, 9, 10)
print(x)
x_val, x_count = np.unique(x, return_counts=True)
print(x_val)
print(x_count)

[4, 9, 1, 4, 5, 1, 5, 7, 0, 5]
[4, 9, 1, 5, 7, 0]
[2, 1, 2, 3, 1, 1]
[5 2 7 7 4 6 0 1 1 7]
[0 1 2 4 5 6 7]
[1 2 1 1 1 1 3]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [4]:
X = np.random.randint(0, 10, (3, 3))
print(X)
Y = np.random.randint(0, 10, (3, 3))
print(Y)

#without numpy
import scipy
print(scipy.spatial.distance.cdist(X, Y)) #быстрее
#numpy
P = np.add.outer(np.sum(X**2, axis=1), np.sum(Y**2, axis=1))
N = np.dot(X, Y.T)
print(np.sqrt(P - 2*N))

[[8 3 5]
 [2 4 2]
 [2 5 2]]
[[4 4 4]
 [5 5 4]
 [0 6 5]]
[[4.24264069 3.74165739 8.54400375]
 [2.82842712 3.74165739 4.12310563]
 [3.         3.60555128 3.74165739]]
[[4.24264069 3.74165739 8.54400375]
 [2.82842712 3.74165739 4.12310563]
 [3.         3.60555128 3.74165739]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [5]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [7]:
average_calories = np.mean(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [9]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [10]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [21]:
nth_percentile = np.percentile(calorie_stats,25)
print(nth_percentile)
nth_percentile = np.percentile(calorie_stats,10)
print(nth_percentile)
nth_percentile = np.percentile(calorie_stats,5)
print(nth_percentile)
nth_percentile = np.percentile(calorie_stats,3)
print(nth_percentile)
nth_percentile = np.percentile(calorie_stats,4)
nth_percentile

100.0
90.0
70.0
55.599999999999994


70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [22]:
more_60_flakes = np.sum(calorie_stats > 60)
all_flakes = len(calorie_stats)
more_calories = more_60_flakes/all_flakes*100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [23]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

In [ ]:
Так как мы знаем среднее значение (107) и стандартное отклонение (19), мы можем утверждать,
что большинство значений находятся в интервале 107+-19, в результате чего мы можем сделать вывод,
что калорийность наших хлопьев (60) значительно ниже большинства хлопьев на рынке.

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Имея все собранные данные мы можем смело утверждать, что калорийность хлопьев нашей компании не только меньше, 
чем у большинства других компаний, но также и значительно ниже чем у большинства конкурентов.
Тем самым мы можем это использовать в своей реклманой кампании для того, чтобы показать насколько наши хлопья
являются некалорийными и здоровыми на фоне остальных вариантов.